mission-apprentissage/bal

Makefile, server/.env.test, server/.mocharc.json, server/package.json, server/src/app.ts, server/src/index.ts, server/src/server.ts, server/tests/integration/example.test.ts, server/tests/routes/users.route.test.ts, server/tests/utils/mocha.utils.ts, server/tests/utils/mongo.utils.ts, server/tsconfig.json, shared/package.json, yarn.lock
#8 
- mocha
- mongodb-memory-server
=> feat: install tests

server/package.json, server/src/modules/server/index.ts, server/tsup.config.ts, yarn.lock
=> feat: ajout swagger

.infra/docker-compose.preview-app.yml, .infra/docker-compose.production.yml, .talismanrc, docker-compose.yml, server/src/modules/data/cli.ts, ui/app/components/NotionDoc.tsx, ui/app/globals.css, ui/app/layout.tsx, ui/app/page.tsx, ui/package.json, yarn.lock
Ajout du mécanisme de notion comme "headless cms"
Ici seulement la front page
=> feat: add notion page as cms

.talismanrc, server/src/modules/actions/users.actions.ts, server/src/modules/server/index.ts, server/src/modules/server/user.routes.ts, server/src/modules/server/utils/auth.strategies.ts, server/tests/routes/auth.route.test.ts, server/tests/routes/users.route.test.ts, shared/routes/user.routes.ts, ui/app/compte/profil/page.tsx
=> feat: improve api key

.talismanrc, server/src/modules/actions/deca.actions.ts, server/src/modules/actions/organisation.actions.ts, server/tests/unit/deca.test.ts
=> feat: verification deca

server/package.json, server/src/modules/actions/users.actions.ts, server/src/modules/server/admin/user.routes.ts, server/src/modules/server/auth.routes.ts, server/src/modules/server/utils/auth.strategies.ts, server/src/utils/mongodb.ts, server/tests/routes/users.route.test.ts, shared/models/user.model.ts, shared/package.json, shared/routes/auth.routes.ts, shared/routes/user.routes.ts, ui/app/components/LoggedIn.tsx, ui/app/compte/profil/page.tsx, ui/app/layout.tsx, ui/context/AuthContext.tsx, ui/package.json, yarn.lock
=> feat: last used date api key

.talismanrc, server/src/modules/actions/documents.actions.ts, server/src/modules/server/admin/upload.routes.ts, server/src/modules/server/admin/user.routes.ts, server/src/modules/server/auth.routes.ts, server/src/modules/server/utils/middleware.utils.ts, server/tests/routes/users.route.test.ts, shared/routes/auth.routes.ts, shared/routes/upload.routes.ts, shared/routes/user.routes.ts, ui/app/admin/fichier/import/page.tsx
=> feat: secure admin routes, clean todo, ts

.talismanrc, server/src/modules/data/processor/document/document.routes.ts, server/src/modules/server/core.routes.ts, server/src/modules/server/v1/organisation.routes.ts, shared/routes/core.routes.ts, ui/app/components/Nav.tsx, ui/app/components/breadcrumb/Breadcrumb.tsx, ui/app/compte/profil/page.tsx, ui/app/layout.tsx, ui/app/usage/healthcheck/page.tsx, ui/app/usage/layout.tsx, ui/app/usage/page.tsx, ui/app/usage/validation/page.tsx, ui/app/usage/verification/page.tsx, ui/components/dialog/Dialog.tsx, ui/theme/icons/ArrowRightLine.tsx, ui/theme/icons/Close.tsx
=> feat: improve api key usage

ui/package.json, yarn.lock
=> chore: upgrade nextjs

server/src/modules/actions/organisations.actions.ts, server/src/modules/server/admin/organisation.routes.ts, server/src/modules/server/admin/person.routes.ts, shared/routes/organisation.routes.ts, shared/routes/person.routes.ts, ui/app/admin/organisations/[id]/components/OrganisationView.tsx, ui/app/admin/organisations/[id]/modifier/components/OrganisationUpdate.tsx, ui/app/admin/organisations/[id]/modifier/page.tsx, ui/app/admin/personnes/[id]/components/PersonView.tsx, ui/app/admin/personnes/[id]/modifier/components/PersonUpdate.tsx, ui/app/admin/personnes/[id]/modifier/page.tsx, ui/app/components/breadcrumb/Breadcrumb.tsx, ui/theme/components/Button.ts
=> WIP feat: update person

.infra/env.ini, .talismanrc, reverse_proxy/app/nginx/templates/includes/location_upload.conf.template, server/src/modules/actions/documents.actions.ts, server/src/modules/actions/mailingLists.actions.ts, shared/constants/index.ts, shared/routes/upload.routes.ts, ui/app/admin/fichier/import/components/Dropzone.tsx, ui/app/liste-diffusion/page.tsx
gestion du fichier de voeux de juin
=> feat: voeux juin

server/src/modules/jobs/jobs.ts, server/src/modules/jobs/seed/clear.ts
=> feat: script clear

.infra/docker-compose.yml, .infra/playbooks/roles/setup/files/app/tools/monitoring/export-cron-status-prom.sh, .infra/playbooks/roles/setup/tasks/configure-backup.yml, .infra/playbooks/roles/setup/tasks/configure-ips-blacklist.yml, .infra/playbooks/roles/setup/tasks/generate-ssl-certificate.yml, .infra/playbooks/roles/setup/tasks/install-app.yml
Envoi des exit status code des CRONs dans prometheus
=> chore: Envoi des status des CRONs dans prometheus

server/src/modules/server/admin/user.routes.ts, server/src/modules/server/auth.routes.ts, server/src/modules/server/mailingList.routes.ts, server/src/modules/server/user.routes.ts, server/src/modules/server/utils/auth.strategies.ts, server/src/modules/server/v1/organisation.routes.ts
=> chore: error handling

docs/deploiement.md, docs/infrastructure.md
Fixes  #175
Documentation de l'infrastructure et de l'environnement de production.
Concernant la documentation il manque https://github.com/mission-apprentissage/bal/issues/201
=> chore: Documentation de l'infrasturcture

server/src/modules/actions/documentContent.actions.ts, server/src/modules/actions/documents.actions.ts, server/src/modules/actions/emails.actions.ts, server/src/modules/actions/organisations.actions.ts, server/src/modules/actions/persons.actions.ts, server/src/modules/actions/sessions.actions.ts, server/src/modules/actions/users.actions.ts, shared/models/session.model.ts, shared/models/user.model.ts
=> feat: timestamps model

.github/workflows/ci.yml, .github/workflows/release.yml
=> chore: Optimisation des Github Actions

docs/deploiement.md, docs/infrastructure.md
Recreate https://github.com/mission-apprentissage/bal/pull/194  due to https://github.com/mission-apprentissage/bal/pull/219
=> chore: Documentation de l'infrasturcture 

.infra/docker-compose.preview.yml, .vscode/launch.json, DEV.md, Makefile, docker-compose.debug.yml, docs/infrastructure.md
=> chore: restore drop commits

server/src/modules/actions/mailingLists.actions.ts
https://www.notion.so/mission-apprentissage/Grouper-par-nom-pr-nom-responsable-1-responsable-2-526b24ddfc3947aa99a06a70cad4e344?pvs=4
=> feat: grouper par email nom prenom

server/src/commands.ts, server/src/common/utils/mongodbUtils.ts, server/src/modules/server/core.routes.ts
La connection mongoDB était closed dans le `postAction` de commander. Il faut quitter l'action uniquement lorsque le server est closed et pas avant.
J'ai aussi ajouté le healthcheck de la connection MongoDB
=> fix: mongodb connection

server/src/modules/actions/documents.actions.ts, server/src/modules/actions/mailingLists.actions.ts, server/src/modules/server/admin/upload.routes.ts, shared/routes/mailingList.routes.ts, shared/routes/upload.routes.ts, ui/app/admin/fichier/import/page.tsx, ui/app/liste-diffusion/components/Form.tsx
https://www.notion.so/mission-apprentissage/En-tant-qu-admin-je-veux-ajouter-un-nouveau-type-de-document-1ed7e6554bfe4b47a326f5920e72c7af?pvs=4
=> feat: importer nouveau type fichier [GENT-27]

.infra/scripts/vault/merge-vault.sh, docs/infrastructure/manage.md
En cas de merge conflict affiche les conflict dans le vault file
=> chore: fix merge vault

.infra/playbooks/deploy.yml, .infra/playbooks/preview_pr.yml
- Prune docker after deployment
- Fix Preview SSL
- Fix missing docker network
=> chore: fix infra

server/src/modules/actions/mailingLists.actions.ts
certains emails ne passaient pas la regex mais sont valides
=> fix: mailing list regex email

server/src/common/utils/parserUtils.ts, server/src/modules/actions/documents.actions.ts
=> feat: reverse delimiter

.bin/scripts/build-images.sh
https://github.com/mission-apprentissage/labonnealternance/pull/707/commits/3c22dd05fe044f9673f64ab768d2113b3627baad
=> feat: clean preview build

.github/workflows/deploy_preview.yml, package.json
husky is required to execute `postinstall` scripts
=> chore: fix release

server/src/modules/actions/documents.actions.ts, server/src/modules/server/admin/upload.routes.ts, server/src/modules/server/server.ts, shared/models/document.model.ts, shared/routes/upload.routes.ts, ui/app/admin/fichier/import/page.tsx, ui/app/admin/fichier/page.tsx, ui/app/liste-diffusion/nouvelle-liste/components/MailingListSectionCell.tsx
- [feat: break words preview](https://www.notion.so/mission-apprentissage/Bouton-supprimer-pas-visible-cl-_me-7e978053726144129a2e43bd48858548?pvs=4)
- [feat: upload display error on file field](https://www.notion.so/mission-apprentissage/Admin-afficher-description-erreur-d-import-f1e33aa470684520a8b1f0c91014f1bb?pvs=4)
- [feat: show error if occurs during content import](https://www.notion.so/mission-apprentissage/Admin-statut-Erreur-d-importation-en-cas-d-erreur-219a54e9a5a74eabb0596cfb7a8c020a?pvs=4)
=> feat: mailing list improvements

server/src/common/utils/parserUtils.ts, server/src/modules/actions/documents.actions.ts, server/src/modules/actions/mailingLists.actions.ts, server/src/modules/server/admin/upload.routes.ts, shared/helpers/mongoSchema/__snapshots__/mongoSchemaBuilder.test.ts.snap, shared/models/document.model.ts, shared/routes/upload.routes.ts, ui/app/admin/fichier/import/page.tsx
https://www.notion.so/mission-apprentissage/Combo-box-choix-de-s-parateur-csv-066629f492eb4fb29d5c000e1676dfd0?pvs=4
=> feat: upload file ask delimiter [GENT-134]

server/src/modules/actions/mailingLists.actions.ts, server/src/modules/server/admin/upload.routes.ts, ui/app/liste-diffusion/nouvelle-liste/components/ChoixColonnesSortie.tsx, ui/app/liste-diffusion/nouvelle-liste/components/WarningEmail.tsx
- https://www.notion.so/mission-apprentissage/Gestion-fichiers-m-me-type-c811ea248e42472281741979f584b370?pvs=4
=> feat: mailing list handle same type file [GENT-137]

.infra/files/configs/mongodb/seed.gpg, .talismanrc, server/src/db/migrations/20231109131100-clear-sessions.ts, server/src/db/migrations/20231109212409-job-discriminator.ts, server/src/modules/actions/job.actions.ts, server/src/modules/server/server.ts, server/src/modules/server/v1/organisation.routes.ts, server/static/emails/common/footer.ejs, shared/helpers/mongoSchema/__snapshots__/mongoSchemaBuilder.test.ts.snap, shared/mailer.ts, shared/routes/index.ts, shared/routes/v1/organisation.routes.ts, ui/app/usage/validation/page.tsx
New route for organisation verification with session is to be discussed
=> fix: verify organisme from UI & reset email

.infra/ansible/deploy.yml
Correction du deploy suite à l'erreur rencontré sur LBA ou les env_var ne sont pas setter correctement + problème sur la valeur CPU du fluentd qui passe d'une string à un int
=> fix: deploy issue

server/src/commands.ts, server/src/modules/jobs/jobs.ts, server/src/modules/jobs/validation/hydrate-from-deca.ts
https://tableaudebord-apprentissage.atlassian.net/jira/software/projects/BAL/boards/10?selectedIssue=BAL-7
=> fix: hydrate deca: ajout offset param

shared/helpers/mongoSchema/__snapshots__/mongoSchemaBuilder.test.ts.snap, shared/models/deca.model/parts/deca.employeur.part.ts
Certains documents ne passent pas la validation. Erreur identifiée sur le champ nombre_de_salaries
=> fix: nombre_de_salaries may be null

.infra/ansible/deploy.yml
Related: https://github.com/mission-apprentissage/infra/pull/53
=> fix: update infra

.infra/docker-compose.preview-system.yml, .infra/docker-compose.preview.yml, .infra/docker-compose.production.yml, .infra/docker-compose.recette.yml, docker-compose.yml
=> feat: remove docker version tag

ui/app/admin/fichier/import/page.tsx, ui/app/liste-diffusion/nouvelle-liste/components/ChoixSource.tsx
- https://tableaudebord-apprentissage.atlassian.net/browse/LBA-2316
=> feat(frontend): add form control

.infra/docker-compose.production.yml
=> feat: add job processor replica

.husky/commitlint.config.js, package.json, server/src/modules/actions/documents.actions.ts, server/src/modules/jobs/deca/hydrate-deca.ts, server/src/modules/jobs/validation/hydrate_from_constructys.ts, server/src/modules/jobs/validation/hydrate_from_ocapiat.ts, server/src/modules/server/admin/upload.routes.ts, server/src/modules/server/mailingList.routes.ts, server/src/modules/server/upload.support.routes.ts, shared/routes/index.ts, shared/routes/mailingList.routes.ts, shared/routes/upload.routes.ts, ui/app/admin/fichier/page.tsx, ui/app/liste-diffusion/components/ListMailingList.tsx
Improves document processing by allowing users to retry failed imports and download existing files.
Also introduces the ability to retry mailing list generation.
These changes streamline the handling of documents and mailing lists, providing a more robust and user-friendly experience.
=> feat: enhances document and mailing list management
